---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/cli
    tag: 'latest'

inputs:
- name: bosh-cli
- name: compiled-linux-amd64
- name: compiled-darwin-amd64
- name: compiled-darwin-arm64
- name: compiled-windows-amd64

outputs:
- name: checksums

run:
  path: bosh-cli/ci/tasks/build-checksum-file.sh
