---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ghcr.io/cloudfoundry/bosh-cli
    tag: 'latest'

inputs:
- name: bosh-cli
- name: version-semver

outputs:
- name: compiled-darwin-arm64

params:
  GOOS:   darwin
  GOARCH: arm64
  FILENAME_PREFIX: ''

run:
  path: bosh-cli/ci/tasks/build.sh
