---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ghcr.io/cloudfoundry/bosh/cli
    tag: 'latest'
    username: ((github_read_write_packages.username))
    password: ((github_read_write_packages.password))

inputs:
- name: bosh-cli
- name: version-semver

outputs:
- name: compiled-linux-amd64

params:
  GOOS:   linux
  GOARCH: amd64
  CGO_ENABLED: 0
  FILENAME_PREFIX: ''

run:
  path: bosh-cli/ci/tasks/build.sh
