---
platform: linux
image_resource:
  type: docker-image
  source: {repository: ghcr.io/cloudfoundry/bosh-cli}
run:
  path: /bin/bash
  args:
  - -c
  - |
    cp compiled-linux-amd64/bosh-cli-* docker-assets/bosh2
    chmod +x docker-assets/bosh2

    cat >docker-assets/Dockerfile <<-FILE
    FROM ubuntu:jammy

    RUN apt-get update && \
      apt-get install -y \
      build-essential \
      ca-certificates \
      libcurl4-openssl-dev \
      libreadline-dev \
      libssl-dev \
      openssl \
      jq \
      zlib1g-dev && \
    apt-get clean

    COPY bosh2 /usr/local/bin/bosh2
    COPY bosh2 /usr/local/bin/bosh
    FILE
inputs:
- name: compiled-linux-amd64
outputs:
- name: docker-assets
