---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ghcr.io/cloudfoundry/bosh-cli
    tag: 'latest'

inputs:
- name: bosh-cli
- name: alpha-release-bucket-linux-amd64

run:
  path: bosh-cli/ci/tasks/test-helper-urls.sh
