---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/docker-cpi
    tag: 'main'

inputs:
- name: bosh-cli
- name: bosh-warden-cpi-release
  path: cpi-release
- name: bosh-warden-stemcell-xenial
  path: stemcell

run:
  path: bosh-cli/ci/tasks/test-acceptance.sh
