---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: bosh/warden-cpi

inputs:
- name: bosh-cli
- name: bosh-warden-cpi-release
  path: cpi-release
- name: stemcell

run:
  path: bosh-cli/ci/tasks/test-acceptance.sh
