---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ghcr.io/cloudfoundry/bosh-cli
    tag: 'latest'
    username: ((github_read_write_packages.username))
    password: ((github_read_write_packages.password))

inputs:
- name: bosh-cli
- name: version-semver
- name: compiled-darwin-amd64
- name: compiled-darwin-arm64
- name: compiled-linux-amd64
- name: homebrew-tap

outputs:
- name: update-brew-formula-output

run:
  path: bosh-cli/ci/tasks/update-homebrew-formula.sh
