---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/cli

inputs:
  - name: bosh-cli-docker-src

outputs:
  - name: docker-files

run:
  path: bosh-cli-docker-src/ci/docker/write-metadata-file.sh

params:
  DOCKER_IMAGE_TAG: latest
